import type { Metadata } from "next"
import { sans } from "@/fonts"
import "./globals.css"

export const metadata: Metadata = {
  title: "Frontend Mentor | Interactive Rating Component",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${sans.className} bg-neutral-black flex min-h-screen flex-col items-center justify-center text-neutral-white px-6`}
      >
        {children}
      </body>
    </html>
  )
}
